### ISSUE TITLE
Migrations connectivity Problem

### ISSUE THREAD

**Issue by whmemon** [sfedosimov/yii2-oci8pdo#1]
This is good extension to work on oracle with Yii. 
I ab able to do basic CRUD with this extension but getting problem with Yii2-user extension migrations.

when i run migration command it gives connectivity error, other wise everything is OK.

The error can be seen at https://github.com/amnah/yii2-user/issues/121

Best Regards,
whmemon

**Comment by sfedosimov** [comment]
Thank you for your comment. In the near future, I'll do it.14:10, 26 декабря 2015 г., whmemon notifications@github.com:This is good extension to work on oracle with Yii  I ab able to do basic CRUD with this extension but getting problem with Yii2-user extension migrations when i run migration command it gives connectivity error, other wise everything is OK The error can be seen at https://githubcom/amnah/yii2-user/issues/121 Best Regards, whmemon —Reply to this email directly or view it on GitHub.     С уважением, Сергей.

**Comment by sfedosimov** [comment]
Hi.Please describe the problem in more detail.As defined above is not enough information. 26.12.2015, 14:10, "whmemon" notifications@github.com:This is good extension to work on oracle with Yii  I ab able to do basic CRUD with this extension but getting problem with Yii2-user extension migrationswhen i run migration command it gives connectivity error, other wise everything is OKThe error can be seen at https://githubcom/amnah/yii2-user/issues/121Best Regards, whmemon—Reply to this email directly or view it on GitHub.   -- С уважением, Сергей.

**Comment by whmemon** [comment]
I have used your extension for Oracle connectivity and able to generate CRUD perfectly. and using it perfectly. 

but when i am using  yii2-user extension and trying to run migration script it gives following error.

in D:\wamp\www\basic\vendor\sfedosimov\yii2-oci8pdo\Oci8PDO.php:93

Stack trace:
#0 D:\wamp\www\basic\vendor\sfedosimov\yii2-oci8pdo\Oci8PDO_Connection.php(39):
yii\db\Connection->createPdoInstance()
#1 D:\wamp\www\basic\vendor\yiisoft\yii2\db\Connection.php(529): sfedosimov\oci8
pdo\Oci8PDO_Connection->createPdoInstance()
#2 D:\wamp\www\basic\vendor\yiisoft\yii2\db\Connection.php(836): yii\db\Connecti
on->open()
#3 D:\wamp\www\basic\vendor\yiisoft\yii2\db\Connection.php(823): yii\db\Connecti
on->getMasterPdo()
#4 D:\wamp\www\basic\vendor\yiisoft\yii2\db\Schema.php(477): yii\db\Connection->
getSlavePdo()
#5 D:\wamp\www\basic\vendor\yiisoft\yii2\db\Connection.php(732): yii\db\Schema->
quoteValue()
#6 D:\wamp\www\basic\vendor\yiisoft\yii2\db\Command.php(172): yii\db\Connection-

The extension amnah/yii2-user works fine with mysql database but make problem with your extension i.e. yii2-oci8pdo. means yii2-oci8pdo gives error when using it with ammah/yii2-user migration script otherwise working fine.

This is actually problem

**Comment by sfedosimov** [comment]
As I understood you adapted the file migration to oracle. Without seeing how you have done the file migration can't understand what the problem is.28.12.2015, 12:29, "whmemon" notifications@github.com:> I have used your extension for Oracle connectivity and able to generate CRUD perfectly. and using it perfectly.>> but when i am using yii2-user extension and trying to run migration script it gives following error.>> in D:\wamp\www\basic\vendor\sfedosimov\yii2-oci8pdo\Oci8PDO.php:93>> Stack trace:> #0 D:\wamp\www\basic\vendor\sfedosimov\yii2-oci8pdo\Oci8PDO_Connection.php(39):> yii\db\Connection->createPdoInstance()> #1 D:\wamp\www\basic\vendor\yiisoft\yii2\db\Connection.php(529): sfedosimov\oci8> pdo\Oci8PDO_Connection->createPdoInstance()> #2 D:\wamp\www\basic\vendor\yiisoft\yii2\db\Connection.php(836): yii\db\Connecti> on->open()> #3 D:\wamp\www\basic\vendor\yiisoft\yii2\db\Connection.php(823): yii\db\Connecti> on->getMasterPdo()> #4 D:\wamp\www\basic\vendor\yiisoft\yii2\db\Schema.php(477): yii\db\Connection->> getSlavePdo()> #5 D:\wamp\www\basic\vendor\yiisoft\yii2\db\Connection.php(732): yii\db\Schema->> quoteValue()> #6 D:\wamp\www\basic\vendor\yiisoft\yii2\db\Command.php(172): yii\db\Connection->> The extension amnah/yii2-user works fine with mysql database but make problem with your extension i.e. yii2-oci8pdo. means yii2-oci8pdo gives error when using it with ammah/yii2-user migration script otherwise working fine.>> This is actually problem>> —> Reply to this email directly or view it on GitHub.-- Sincerely, Sergey.

**Comment by whmemon** [comment]
Executing following command after that get the connectivity error.

php yii migrate --migrationPath=@vendor/amnah/yii2-user/migrations

**Comment by sfedosimov** [comment]
Did you try to do as described here (http://www.yiiframework.com/doc-2.0/guide-db-migrations.html#migrating-multiple-databases)?

**Comment by whmemon** [comment]
Resolved.
